load("@aspect_bazel_lib//lib:transitions.bzl", "platform_transition_binary")
load("@rules_cc//cc:defs.bzl", "cc_binary")

package(default_visibility = ["//visibility:public"])

ARCHS = [
    "x86_64",
    "aarch64",
]

cc_binary(
    name = "runtime",
    srcs = ["src/runtime/runtime.c"],
    additional_linker_inputs = ["src/runtime/data_sections.ld"],
    linkopts = ["-T$(rootpath src/runtime/data_sections.ld)"],
    local_defines = [
        "FUSE_USE_VERSION=316",
        "GIT_COMMIT=\\\"" + module_version() + "\\\"",
    ],
    deps = [
        "@libfuse",
        "@squashfuse",
        "@zlib",
        "@zstd",
    ],
)

[
    platform_transition_binary(
        name = "runtime_" + arch,
        binary = ":runtime",
        target_platform = "@toolchains_llvm_bootstrapped//platforms/libc_aware:linux_{}_musl".format(arch),
    )
    for arch in ARCHS
]

filegroup(
    name = "runtimes",
    srcs = [":runtime_" + arch for arch in ARCHS],
)
