name: build

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: ${{ github.ref_name != 'main' && github.event.action == 'synchronize' }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - uses: bazel-contrib/setup-bazel@0.19.0
      with:
        bazelisk-cache: true
        disk-cache: ${{ github.workflow }}
        repository-cache: true
    
    - name: Build multi-platform runtimes
      run: bazel build --compilation_mode opt //:runtimes
    
    - uses: actions/upload-artifact@v4
      with:
        name: runtimes
        path: |
          bazel-bin/runtime_x86_64/runtime
          bazel-bin/runtime_aarch64/runtime

  required:
    runs-on: ubuntu-slim
    needs: [build]
    if: always()
    steps:
    - name: Fail if any ancestor job failed
      if: ${{ contains(needs.*.result, 'failure') || contains(needs.*.result, 'cancelled') }}
      run: exit 1
