name: build

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

# This ensures that jobs get canceled when force-pushing
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v5
    
    - name: Build multi-platform runtimes
      run: bazel build --compilation_mode opt //:runtimes
    
    - uses: actions/upload-artifact@v4
      with:
        name: runtimes
        path: |
          bazel-bin/runtime_x86_64/runtime
          bazel-bin/runtime_aarch64/runtime
