name: build

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - uses: bazel-contrib/setup-bazel@0.19.0
      with:
        bazelisk-cache: true
        disk-cache: ${{ github.workflow }}
        repository-cache: true
    
    - name: Build multi-platform runtimes
      run: bazel build --compilation_mode opt //:runtimes
    
    - uses: actions/upload-artifact@v4
      with:
        name: runtimes
        path: |
          bazel-bin/runtime_x86_64/runtime
          bazel-bin/runtime_aarch64/runtime
