name: build

on:
  push:
    branches:
      - "main"
  pull_request:

# This ensures that jobs get canceled when force-pushing
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

# The default Debian shell (dash) is faster than bash at running scripts,
# and using bash when it is not needed doesn't make sense.
defaults:
  run:
    shell: sh

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        arch: [aarch64, armv7, i686, x86_64]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Get git hash
        run: |
          VERSION="$(date --utc +%Y-%m-%d)-$(git rev-parse --short HEAD)"
          echo -n "https://github.com/${GITHUB_REPOSITORY}/releases/tag/build-${VERSION}" > src/runtime/version
          echo "${VERSION}" > tag.txt

      - name: Build
        uses: lalten/run-on-arch-action@amd64-support # should be switched to `uraimo/run-on-arch-action@v2` when https://github.com/uraimo/run-on-arch-action/pull/94 is merged
        with:
          arch: ${{ matrix.arch }}
          distro: alpine_latest
          dockerRunArgs: |
            --volume "${PWD}/out:/out"
          run: ./build.sh

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: artifacts
          path: ./out/*

      - name: Create Release
        if: github.event_name != 'pull_request' && github.ref_name == 'main'
        run: |
          VERSION="$(cat tag.txt)"
          TAG="build-${VERSION}"
          if gh release view "${TAG}" > /dev/null; then
            gh release upload  "${TAG}" out/*
          else
            gh release create --prerelease --title "Build ${VERSION}"  "${TAG}" out/*
          fi
